import { formatPRBody } from '../../src/services/prFormatter.service.js';

describe('PR Formatter Service', () => {
  test('should format basic PR body with test count', () => {
    const stats = { testCount: 5 };
    const body = formatPRBody(stats);
    
    expect(body).toContain('## 🤖 Automated Test Generation');
    expect(body).toContain('This PR adds **5** generated test cases.');
    expect(body).toContain('*Generated by GitHub Test Case Generator*');
  });

  test('should include functions covered', () => {
    const stats = { 
      testCount: 3, 
      functionsCovered: ['login', 'logout'] 
    };
    const body = formatPRBody(stats);
    
    expect(body).toContain('### 🎯 Functions Covered');
    expect(body).toContain('- `login`');
    expect(body).toContain('- `logout`');
  });

  test('should include improvements as list', () => {
    const stats = { 
      testCount: 1, 
      improvements: ['Added edge case', 'Fixed typo'] 
    };
    const body = formatPRBody(stats);
    
    expect(body).toContain('### 💡 Improvements');
    expect(body).toContain('- Added edge case');
    expect(body).toContain('- Fixed typo');
  });

  test('should include coverage delta', () => {
    const stats = { 
      testCount: 10, 
      coverageDelta: '+12%' 
    };
    const body = formatPRBody(stats);
    
    expect(body).toContain('### 📊 Coverage Delta');
    expect(body).toContain('Expected change: **+12%**');
  });

  test('should handle all fields together', () => {
    const stats = {
      testCount: 42,
      functionsCovered: ['processData'],
      improvements: 'Better performance',
      coverageDelta: '2%'
    };
    const body = formatPRBody(stats);

    expect(body).toContain('**42** generated test cases');
    expect(body).toContain('- `processData`');
    expect(body).toContain('Better performance');
    expect(body).toContain('**2%**');
  });
});
