/**
 * Formats the Pull Request body with structured markdown statistics.
 * 
 * @param {Object} params
 * @param {number} params.testCount - Number of tests generated
 * @param {string[]} [params.functionsCovered] - List of functions covered
 * @param {string|string[]} [params.improvements] - Summary of improvements
 * @param {string|number} [params.coverageDelta] - Optional coverage delta (e.g. "+5%")
 * @returns {string} Formatted markdown string
 */
export function formatPRBody({ testCount, functionsCovered = [], improvements = [], coverageDelta }) {
  const sections = [];

  // Header
  sections.push(`## 🤖 Automated Test Generation`);
  sections.push(`This PR adds **${testCount}** generated test cases.`);

  // Functions Covered
  if (functionsCovered && functionsCovered.length > 0) {
    sections.push(`### 🎯 Functions Covered`);
    const list = functionsCovered.map(f => `- \`${f}\``).join('\n');
    sections.push(list);
  }

  // Improvements
  if (improvements) {
    sections.push(`### 💡 Improvements`);
    if (Array.isArray(improvements) && improvements.length > 0) {
      sections.push(improvements.map(i => `- ${i}`).join('\n'));
    } else if (typeof improvements === 'string' && improvements.trim().length > 0) {
      sections.push(improvements);
    }
  }

  // Coverage Delta
  if (coverageDelta) {
    sections.push(`### 📊 Coverage Delta`);
    sections.push(`Expected change: **${coverageDelta}**`);
  }

  // Footer
  sections.push(`---`);
  sections.push(`*Generated by GitHub Test Case Generator*`);

  return sections.join('\n\n');
}
